#! python


def build(ctx):

    for s in [
        "Dissertation/dissertation",
        # "Presentation/presentation",
        # "CV",
        # "Declaration"
    ]:
        ctx(
            features="tex",
            source=s + ".tex",
            prompt=1,
            name=s,
            deps=[],
        )
        # Install to the project root.
        ctx.install_files(ctx.env.PROJECT_PATHS["PROJECT_ROOT"].abspath(), s + ".pdf")
